### PR TITLE
convert ghostdriver cookie tests to python

### PR DESCRIPTION
**Pull request by jesg**
- should_be_able_to_create_cookie_via_javascript and should_allow_to_delete_cookies_even_if_not_set refactored so they do not depend upon an external website

### CODE REVIEW

**Comment by zackw** [comment]
Merged, thank you.

**Comment by zackw** [comment]
(FYI, we don't use the "merge" button because we want to keep the history as linear as practical.)

**Comment by jesg** [comment]
cool.  i'll work on some of the other tests when i get the time.

**Comment by zackw** [comment]
Much appreciated.

**Pull request closed without merging**
